### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [juhp/http-query#1]
```
http-query                > /tmp/stack-cd4cffbc28412421/http-query-0.1.0.1/src/Network/HTTP/Query.hs:99:30: error:
http-query                >     • Couldn't match expected type ‘Key’ with actual type ‘Text’
http-query                >     • In the second argument of ‘(.:)’, namely ‘k’
http-query                >       In the first argument of ‘parseMaybe’, namely ‘(.: k)’
http-query                >       In the expression: parseMaybe (.: k)
http-query                >    |
http-query                > 99 | lookupKey k = parseMaybe (.: k)
http-query                >    |                              ^
http-query                > 
http-query                > /tmp/stack-cd4cffbc28412421/http-query-0.1.0.1/src/Network/HTTP/Query.hs:103:37: error:
http-query                >     • Couldn't match expected type ‘Key’ with actual type ‘Text’
http-query                >     • In the second argument of ‘(.:)’, namely ‘k’
http-query                >       In the first argument of ‘parseEither’, namely ‘(.: k)’
http-query                >       In the expression: parseEither (.: k)
http-query                >     |
http-query                > 103 | lookupKeyEither k = parseEither (.: k)
http-query                >     |                                     ^
http-query                > 
http-query                > /tmp/stack-cd4cffbc28412421/http-query-0.1.0.1/src/Network/HTTP/Query.hs:108:37: error:
http-query                >     • Couldn't match expected type ‘Key’ with actual type ‘Text’
http-query                >     • In the second argument of ‘(.:)’, namely ‘k’
http-query                >       In the first argument of ‘parseEither’, namely ‘(.: k)’
http-query                >       In the second argument of ‘(.)’, namely ‘parseEither (.: k)’
http-query                >     |
http-query                > 108 |   either error id . parseEither (.: k)
http-query                >     |                                     ^
```

**Comment by juhp** [comment]
Fixed by [0.1.1](https://hackage.haskell.org/package/http-query-0.1.1)
